//Manage the ObjectBox store
import '../models/stock_item.dart';
import '../models/user_model.dart';
import '../objectbox_model.dart'; 

class ObjectBoxService {
  late final Store store;

  //Boxes or table or collectins
  late final Box<UserModel> userBox;
  late final Box<StockItem> itemBox;

  ObjectBoxService._create(this.store) {
    userBox = Box<UserModel>(store);
    itemBox = Box<StockItem>(store);
  }

  static Future<ObjectBoxService> create() async {
    final store = await openStore(); // auto-generated by ObjectBox
    return ObjectBoxService._create(store);
  }
}